services:
  - type: web
    name: device_expansion
    env: docker
    plan: starter
    buildCommand: |
      if [ "$RAILS_ENV" = "production" ]; then
        bundle install
        yarn install
        yarn add esbuild
        yarn build
        bundle exec rails assets:precompile
      else
        echo "Skipping assets precompilation in non-production environment"
      fi
    startCommand: |
      bundle exec puma -C config/puma.rb
