services:
  web:
    env_file:
      - .env.production
    command: |
      bash -c "bundle exec rails db:migrate RAILS_ENV=production && bundle exec puma -C config/puma.rb"
    volumes:
      - "./shared/public:/app/public"
