services:
  db:
    image: postgres:14.13
    ports:
      - "5432:5432"
    volumes:
      - "${POSTGRES_DATA_DIR:-./postgres_data}:/var/lib/postgresql/data"
    env_file:
      - .env.production
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -h localhost -d production_db || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: ["bundle", "exec", "puma", "-C", "config/puma.rb"]
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.production
    restart: always
