FROM ruby:3.1.0
RUN apt-get update -qq && apt-get install -y \
    libpq-dev postgresql-client curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY Gemfile Gemfile.lock /app/
RUN bundle config set path 'vendor/bundle' \
    && bundle install --jobs 4 --retry 3
COPY . /app
ENV RAILS_ENV production
ENV PATH ./vendor/bundle/ruby/3.1.0/bin:$PATH
EXPOSE 3000
