services:
  - type: web
    name: device_expansion
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile.production
    preDeployCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
