services:
  - type: web
    name: device_expansion
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile.production
    preDeployCommand: |
      export NODE_ENV=production
      export SECRET_KEY_BASE=${SECRET_KEY_BASE}

      if [ -f tmp/pids/server.pid ]; then
        rm -f tmp/pids/server.pid
      fi

      echo "Installing Ruby gems..."
      bundle install --jobs 4 --retry 3 || { echo "Bundle install failed"; exit 1; }

      echo "Installing importmap..."
      bin/rails importmap:install || { echo "Importmap install failed"; exit 1; }

      echo "Compiling assets using Rake task..."
      bundle exec rake assets:precompile || { echo "Asset precompilation failed"; exit 1; }

      echo "Running database migrations..."
      bundle exec rails db:migrate || { echo "Migration failed"; exit 1; }

      echo "Seeding the database..."
      bundle exec rails db:seed || { echo "Seeding failed"; exit 1; }
