services:
  - type: web
    name: device_expansion
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile.production
    preDeployCommand: |
      sh -c 'test -f tmp/pids/server.pid && rm -f tmp/pids/server.pid'

      echo "Installing Ruby gems..."
      NODE_ENV=production SECRET_KEY_BASE=${SECRET_KEY_BASE} bundle install --jobs 4 --retry 3 || { echo "Bundle install failed"; exit 1; }

      echo "Installing importmap..."
      NODE_ENV=production SECRET_KEY_BASE=${SECRET_KEY_BASE} bin/rails importmap:install || { echo "Importmap install failed"; exit 1; }

      echo "Compiling assets using Rake task..."
      NODE_ENV=production SECRET_KEY_BASE=${SECRET_KEY_BASE} bundle exec rake assets:precompile || { echo "Asset precompilation failed"; exit 1; }

      echo "Running database migrations..."
      NODE_ENV=production SECRET_KEY_BASE=${SECRET_KEY_BASE} bundle exec rails db:migrate || { echo "Migration failed"; exit 1; }

      echo "Seeding the database..."
      NODE_ENV=production SECRET_KEY_BASE=${SECRET_KEY_BASE} bundle exec rails db:seed || { echo "Seeding failed"; exit 1; }
