services:
  - type: web
    name: device_expansion
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile.production
    preDeployCommand: |
      set -o errexit

      export NODE_ENV=production
      export SECRET_KEY_BASE=${SECRET_KEY_BASE}

      if [ -f tmp/pids/server.pid ]; then
        rm -f tmp/pids/server.pid
      fi

      echo "Installing Ruby gems..."
      bundle install --jobs 4 --retry 3 || { echo "Bundle install failed"; exit 1; }

      echo "Installing importmap..."
      bin/rails importmap:install

      echo "Building assets..."
      yarn build

      echo "Compiling assets..."
      bundle exec rails assets:precompile

      echo "Running database migrations..."
      bundle exec rails db:migrate

      echo "Seeding the database..."
      bundle exec rails db:seed
